# Site settings
title: Bharath S

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Bharath33
 - title: LinkedIn
   url: www.linkedin.com/in/bharath-selvam
